import { NextRequest, NextResponse } from 'next/server';import { randomUUID } from 'node:crypto';import { governedQuery, governedTransaction } from '@/lib/governedPostgres';
// eslint-disable-next-line @typescript-eslint/no-require-imports
const {KEY,digest,verifyIdentity,canTransition,provenanceErrors,retryState}=require('../../../../../governance/kernel.cjs');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const {evaluate}=require('../../../../../governance/domain.cjs');
const AUDIENCE='agent-governance';const WORKFLOW='policy-obligation-release';const PROVIDERS=new Set(['regulatory-registry','contract-repository','identity-provider','notification','audit-export']);const APPROVERS=new Set(['governance_manager','compliance_officer','legal_reviewer','admin']);
function context(request:NextRequest){return verifyIdentity(request.headers,process.env.GOVERNANCE_GATEWAY_SECRET||'',AUDIENCE)}
export async function GET(request:NextRequest){const ctx=context(request);if(!ctx)return NextResponse.json({error:'signed governance identity required'},{status:401});const rows=await governedQuery('SELECT id,owner_id,state,version,result,uncertainty,created_by,approved_by,updated_at FROM governed_work_items WHERE tenant_id=$1 AND workflow_type=$2 ORDER BY updated_at DESC LIMIT 100',[ctx.tenant,WORKFLOW]);return NextResponse.json(rows.rows)}
export async function POST(request:NextRequest){const ctx=context(request);if(!ctx)return NextResponse.json({error:'signed governance identity required'},{status:401});const key=request.headers.get('Idempotency-Key')||'';if(!KEY.test(key))return NextResponse.json({error:'valid Idempotency-Key required'},{status:400});try{const body=await request.json();
if(body.action==='source-ingest'){if(!ctx.permissions.includes('source:ingest')||!PROVIDERS.has(body.provider))return NextResponse.json({error:'source permission and provider required'},{status:403});const pErrors=provenanceErrors(body.provenance);if(pErrors.length)return NextResponse.json({errors:pErrors},{status:422});const hash=digest({provider:body.provider,sourceId:body.sourceId,sourceVersion:body.sourceVersion,provenance:body.provenance});const result=await governedQuery('INSERT INTO governed_sources(tenant_id,id,provider,source_id,source_version,effective_at,jurisdiction,payload_hash,provenance,freshness_at,deleted_at_source) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(tenant_id,provider,source_id) DO UPDATE SET source_version=EXCLUDED.source_version,effective_at=EXCLUDED.effective_at,jurisdiction=EXCLUDED.jurisdiction,payload_hash=EXCLUDED.payload_hash,provenance=EXCLUDED.provenance,freshness_at=EXCLUDED.freshness_at,deleted_at_source=EXCLUDED.deleted_at_source RETURNING *',[ctx.tenant,randomUUID(),body.provider,body.sourceId,body.sourceVersion,body.effectiveAt,body.jurisdiction,hash,body.provenance,body.freshnessAt,body.deletedAtSource||null]);return NextResponse.json(result.rows[0])}
if(body.action==='create'){if(!ctx.permissions.includes('work:create'))return NextResponse.json({error:'work:create permission required'},{status:403});const assessed=evaluate(body.input);if(assessed.errors.length)return NextResponse.json(assessed,{status:422});const hash=digest({ownerId:body.ownerId,input:body.input});const created=await governedTransaction(async q=>{const result=await q<any>('WITH inserted AS (INSERT INTO governed_work_items(tenant_id,id,workflow_type,owner_id,input,result,uncertainty,request_hash,idempotency_key,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(tenant_id,workflow_type,idempotency_key) DO NOTHING RETURNING *) SELECT *,FALSE replay FROM inserted UNION ALL SELECT *,TRUE replay FROM governed_work_items WHERE tenant_id=$1 AND workflow_type=$3 AND idempotency_key=$9 AND request_hash=$8 AND NOT EXISTS(SELECT 1 FROM inserted) LIMIT 1',[ctx.tenant,randomUUID(),WORKFLOW,body.ownerId,body.input,assessed.result,assessed.uncertainty,hash,key,ctx.actor]);if(result.rows[0]&&!result.rows[0].replay)await q('INSERT INTO governed_decisions(tenant_id,work_item_id,actor_id,event_type) VALUES($1,$2,$3,\'created\')',[ctx.tenant,result.rows[0].id,ctx.actor]);return result.rows[0]});return created?NextResponse.json(created,{status:created.replay?200:201}):NextResponse.json({error:'idempotency conflict'},{status:409})}
if(body.action==='transition'){const to=String(body.to||'');const reason=String(body.reason||'').trim();if(!reason)return NextResponse.json({error:'reason required'},{status:422});const changed=await governedTransaction(async q=>{const current=await q<any>('SELECT * FROM governed_work_items WHERE tenant_id=$1 AND id=$2 AND workflow_type=$3 FOR UPDATE',[ctx.tenant,body.id,WORKFLOW]);const item=current.rows[0];if(!item||item.version!==Number(body.version)||!canTransition(item.state,to))return null;if(['approved','rejected'].includes(to)&&(!APPROVERS.has(ctx.role)||item.created_by===ctx.actor))return null;if(to==='released'&&!ctx.permissions.includes('work:release'))return null;const result=await q<any>('UPDATE governed_work_items SET state=$1,version=version+1,approved_by=CASE WHEN $1=\'approved\' THEN $2 ELSE approved_by END,updated_at=NOW() WHERE tenant_id=$3 AND id=$4 AND version=$5 AND ($1<>\'approved\' OR created_by<>$2) RETURNING *',[to,ctx.actor,ctx.tenant,body.id,Number(body.version)]);if(!result.rowCount)return null;await q('INSERT INTO governed_decisions(tenant_id,work_item_id,actor_id,event_type,reason) VALUES($1,$2,$3,$4,$5)',[ctx.tenant,body.id,ctx.actor,to,reason.slice(0,1000)]);if(to==='released')await q('INSERT INTO governed_outbox(tenant_id,work_item_id,provider,operation,payload,idempotency_key) VALUES($1,$2,\'audit-export\',\'export\',$3,$4) ON CONFLICT DO NOTHING',[ctx.tenant,body.id,{workItemId:body.id},`${body.id}:${body.version}:release`]);return result.rows[0]});return changed?NextResponse.json(changed):NextResponse.json({error:'missing, stale, unauthorized, or invalid transition'},{status:409})}
if(body.action==='delivery-result'){if(!ctx.permissions.includes('provider:result'))return NextResponse.json({error:'provider permission required'},{status:403});if(body.status==='delivered'&&(!body.receipt?.receiptRef||!body.receipt?.receivedAt))return NextResponse.json({error:'typed receipt required'},{status:422});const status=body.status==='delivered'?'delivered':retryState(Number(body.attempt),body.retryable!==false);const result=await governedQuery('UPDATE governed_outbox SET status=$1,attempts=attempts+1,provider_receipt=$2,last_error_code=$3,lease_token=NULL,lease_expires_at=NULL,next_attempt_at=NOW()+INTERVAL \'1 minute\' WHERE tenant_id=$4 AND id=$5 RETURNING *',[status,body.receipt||null,body.errorCode||null,ctx.tenant,body.outboxId]);return result.rowCount?NextResponse.json(result.rows[0]):NextResponse.json({error:'outbox item not found'},{status:404})}
return NextResponse.json({error:'unsupported action'},{status:422})}catch(error){console.error('governed workflow failed',error instanceof Error?error.name:'unknown');return NextResponse.json({error:'governed workflow failed'},{status:500})}}
